### ISSUE TITLE
Crash with Firefox

### ISSUE THREAD

**Issue by Faylixe** [Faylixe/googlecodejam-cli#1]
Error reported using Firefox _45.0.1_

```
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Mikloss-MacBook-Pro.local', ip: '192.168.0.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: driver.version: FirefoxDriver
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:135)
at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
at fr.faylixe.googlecodejam.cli.ApplicationCommand$$Lambda$1/565760380.get(Unknown Source)
at fr.faylixe.googlecodejam.cli.SeleniumCookieSupplier.get(SeleniumCookieSupplier.java:64)
at fr.faylixe.googlecodejam.cli.ApplicationCommand.init(ApplicationCommand.java:110)
at fr.faylixe.googlecodejam.cli.Application.main(Application.java:37)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
UG  getModTime: Recursive scan of loop@mozilla.org
1459443105568   addons.xpi  DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"J-yA4AK5PBCt","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458727929000,"updateDate":1458727929000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
1459443105568   addons.xpi  DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1459443105568   DeferredSave.extensions.json    DEBUG   Save changes
1459443105568   addons.xpi  DEBUG   Updating database with changes to installed add-ons
1459443105568   addons.xpi-utils    DEBUG   Updating add-on states
1459443105569   addons.xpi-utils    DEBUG   Writing add-ons list
1459443105570   addons.xpi  DEBUG   Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1459443105570   addons.xpi  DEBUG   Calling bootstrap method startup on loop@mozilla.org version 0.1
1459443105583   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1459443105583   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1459443105584   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1459443105597   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1459443105597   addons.manager  DEBUG   Provider finished startup: XPIProvider
1459443105597   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1459443105597   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1459443105597   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1459443105598   addons.manager  DEBUG   Starting provider: GMPProvider
1459443105602   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1459443105603   addons.manager  DEBUG   Provider finished startup: GMPProvider
1459443105603   addons.manager  DEBUG   Starting provider: PluginProvider
1459443105603   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1459443105603   addons.manager  DEBUG   Provider finished startup: PluginProvider
1459443105603   addons.manager  DEBUG   Completed startup sequence
1459443106080   DeferredSave.extensions.json    DEBUG   Starting write
1459443106229   addons.repository   DEBUG   No addons.json found.
1459443106230   DeferredSave.addons.json    DEBUG   Save changes
1459443106233   DeferredSave.addons.json    DEBUG   Starting timer
1459443106260   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1459443106260   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1459443106260   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1459443106262   DeferredSave.extensions.json    DEBUG   Write succeeded
1459443106262   addons.xpi-utils    DEBUG   XPI Database saved, setting schema version preference to 17
1459443106287   DeferredSave.addons.json    DEBUG   Starting write
1459443106296   DeferredSave.addons.json    DEBUG   Write succeeded
JavaScript warning: chrome://browser/content/browser-places.js, line 640: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
JavaScript error: chrome://browser/content/places/browserPlacesViews.js, line 263: TypeError: this.controller is undefined
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
... 10 more
```

**Comment by Faylixe** [comment]
Solved by release 1.1.1 (selenium version issues).
