### ISSUE TITLE
UnsupportedClassVersionError when launching the tool (Ubuntu Wily, Java 1.7)

### ISSUE THREAD

**Issue by alexdu** [Faylixe/googlecodejam-cli#6]
I've tried your tool during qualification round, installed today using the install script.

```
wget -O - https://raw.githubusercontent.com/Faylixe/googlecodejam-cli/master/scripts/install | sudo bash
--2016-04-09 20:35:34--  https://raw.githubusercontent.com/Faylixe/googlecodejam-cli/master/scripts/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1109 (1.1K) [text/plain]
Saving to: ‘STDOUT’

-                               100%[=======================================================>]   1.08K  --.-KB/s   in 0s     

2016-04-09 20:35:35 (95.8 MB/s) - written to stdout [1109/1109]

##############################################
# Google Code Jam Client installation script #
##############################################

> Removing existing artifact /usr/local/bin/googlecodejam-cli.jar
> Downloading released JAR archive from GitHub
> Removing existing script /usr/local/bin/codejam/
> Downloading last script version from GitHub

Installation complete, you can now run the 'codejam' command
```

```
codejam --init --contest 6254486
Exception in thread "main" java.lang.UnsupportedClassVersionError: fr/faylixe/googlecodejam/cli/Application : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

```
java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

It seems to be some dependency problem, rather than an incompatibility with the code jam website. Do I need another Java version? How do I find out which one?

**Comment by Faylixe** [comment]
This tool requires Java 8. You should update your Java version and it should work. Alhough do not use it during the qualification round, there is a critical issue : source file are not uploaded correctly with the solution (the submission are still accepted though so i have no clue about the consequence of it). I will have it fixed for the next round (1A).

**Comment by Faylixe** [comment]
My bad i didn't mentioned it on the installation detail, i will update the README.

**Comment by alexdu** [comment]
Thanks; I ran `sudo apt-get install openjdk-8-jre` and seems to work now.

Would be nice if the installer could warn you about it, or if the error message was clearer.

**Comment by Faylixe** [comment]
Thanks for the advice i will update the installation script asap.

**Comment by alexdu** [comment]
Not a native English speaker, but doesn't "prior" (as in, "It requires Java 8 and prior") mean "older"?

Also, I guess it doesn't require both versions (so, Java 8 _or_ later/newer/whatever).

**Comment by veltzerdoron** [comment]
Don't be a dick
