### ISSUE TITLE
Contest Init Fails

### ISSUE THREAD

**Issue by alayouni** [Faylixe/googlecodejam-cli#9]
I'm under OSX El Capitain v10.11.6, when I run java -jar googlecodejam-cli.jar --init firefox open up with a blank screen, and I get the below in command line:

1492886866430	geckodriver	INFO	Listening on 127.0.0.1:37215
1492886866622	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1492886867701	Marionette	INFO	Listening on port 62434
2017-04-22 19:47:49.258 plugin-container[19091:426267] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x953f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-22 19:47:49.260 plugin-container[19091:426267] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x5027, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-22 19:47:49.260 plugin-container[19091:426267] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=null}}], required capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=null}}]
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Ahmeds-MacBook-Pro.local', ip: '192.168.1.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
	at fr.faylixe.googlecodejam.cli.SeleniumCookieSupplier.get(SeleniumCookieSupplier.java:66)
	at fr.faylixe.googlecodejam.cli.ApplicationCommand.browserInit(ApplicationCommand.java:214)
	at fr.faylixe.googlecodejam.cli.ApplicationCommand.init(ApplicationCommand.java:273)
	at fr.faylixe.googlecodejam.cli.Application.main(Application.java:53)

**Comment by alayouni** [comment]
Just submitted a [pull request](https://github.com/Faylixe/googlecodejam-cli/pull/10) with a fix.
